-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'SESSION_TERMINATED';
ALTER TYPE "AuditAction" ADD VALUE 'VALIDATOR_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'SUSPICIOUS_ACTIVITY';
ALTER TYPE "AuditAction" ADD VALUE 'SECURITY_BREACH';
ALTER TYPE "AuditAction" ADD VALUE 'DATA_BREACH';
ALTER TYPE "AuditAction" ADD VALUE 'UNAUTHORIZED_ACCESS';
ALTER TYPE "AuditAction" ADD VALUE 'FORBIDDEN_ACTION';
ALTER TYPE "AuditAction" ADD VALUE 'RESOURCE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'RESOURCE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'RESOURCE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'RESOURCE_ACCESSED';
ALTER TYPE "AuditAction" ADD VALUE 'RESOURCE_PERMISSION_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'SYSTEM_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'VALIDATION_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'AUTHENTICATION_FAILURE';
ALTER TYPE "AuditAction" ADD VALUE 'AUTHORIZATION_FAILURE';
ALTER TYPE "AuditAction" ADD VALUE 'RATE_LIMIT_HIT';
ALTER TYPE "AuditAction" ADD VALUE 'SERVICE_UNAVAILABLE';
ALTER TYPE "AuditAction" ADD VALUE 'DATABASE_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'EXTERNAL_API_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'CACHE_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'CONFIGURATION_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'DEPLOYMENT';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'RESTORE_STARTED';
ALTER TYPE "AuditAction" ADD VALUE 'RESTORE_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'RESTORE_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'MAINTENANCE_MODE_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE 'MAINTENANCE_MODE_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_ROLE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'PERMISSION_GRANTED';
ALTER TYPE "AuditAction" ADD VALUE 'PERMISSION_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE 'API_KEY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'API_KEY_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE 'WEBHOOK_RECEIVED';
ALTER TYPE "AuditAction" ADD VALUE 'WEBHOOK_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'MIDDLEWARE_FAILURE';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_ERROR';
ALTER TYPE "AuditAction" ADD VALUE 'SESSION_VALIDATOR_ERROR';
